#!/bin/bash
#alias NICKNAME='COMMAND'

#color support
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='colordiff' #requires colordiff package

#human sizes
alias df='df -h'
alias du='du -h'
alias free='free -m'

#modified commands
alias more='less'
#alias df='df -h'
#alias du='du -c -h'
#alias mkdir='mkdir -p -v'
#alias nano='nano -w'
#alias ping='ping -c 5'
alias ..='cd ..'

#shortcuts
alias c='clear'
alias e='exit'
alias ka='killall'
alias db='dropbox'
alias dbp='dropbox puburl'
alias ns='notify-send'
alias nsc='notify-send "Process Completed"'
alias h='history'
alias ra='ranger'

#new commands
alias lock='xscreensaver-command -lock'
alias xmerge='xrdb -merge $HOME/.xresources'
alias pig='ping google.com'
alias help='cat ~/.help'
alias du1='du -h --max-depth=1'
alias hist='history | grep $1'      # requires an argument
alias openports='netstat --all --numeric --programs --inet --inet6'
#alias pg='ps -Af | grep $1'         # requires an argument (note: /usr/bin/pg is installed by the util-linux package; maybe a different alias name should be used)

#privileged access
if [ $UID -ne 0 ]; then
    alias sudo='sudo '
    alias scat='sudo cat'
    alias svim='sudo vim'
    alias root='sudo su'
    alias reboot='sudo reboot'
    alias halt='sudo halt'
    #alias update='sudo pacman -Su'
    #alias netcfg='sudo netcfg2'
fi

#safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

#vim
alias vimall='vim -p *'
alias vimp='vim -p'
alias vimh='vim -o'
alias vimv='vim -O'
alias vimd='vim -d'

#feh
alias feh='feh --scale-down --auto-zoom'

#ls
alias ls='ls -hF --color=auto'
alias lr='ls -R'                    # recursive ls
alias ll='ls -l'
alias la='ls -A'
alias lal='ls -Al'
alias lx='ll -BX'                   # sort by extension
alias lz='ll -rS'                   # sort by size
alias lt='ll -rt'                   # sort by date
alias lm='la | less'

#pacman/packer
alias pcm='sudo pacman'
alias pcr='packer --noedit --auronly'

#pacman aliases (if applicable, replace 'pacman' with 'yaourt'/'pacaur'/whatever)
#alias pac='pacman -S'      # default action     - install one or more packages
#alias pacu='pacman -Syu'   # '[u]pdate'         - upgrade all packages to their newest version
#alias pacs='pacman -Ss'    # '[s]earch'         - search for a package using one or more keywords
#alias paci='pacman -Si'    # '[i]nfo'           - show information about a package
#alias pacr='pacman -R'     # '[r]emove'         - uninstall one or more packages
#alias pacl='pacman -Sl'    # '[l]ist'           - list all packages of a repository
#alias pacll='pacman -Qqm'  # '[l]ist [l]ocal'   - list all packages which were locally installed (e.g. AUR packages)
#alias paclo='pacman -Qdt'  # '[l]ist [o]rphans' - list all packages which are orphaned
#alias paco='pacman -Qo'    # '[o]wner'          - determine which package owns a given file
#alias pacf='pacman -Ql'    # '[f]iles'          - list all files installed by a given package
#alias pacc='pacman -Sc'    # '[c]lean cache'    - delete all not currently installed package files
#alias pacm='makepkg -fci'  # '[m]ake'           - make package from PKGBUILD file in current directory

# bash aliases
if [ -f ~/.aliases.personal ]; then
	. ~/.aliases.personal
fi
