#!/bin/sh

echo "Installing homesick..."
gem install homesick
echo

if [ -d "$HOME/.homesick/repos/dotfiles" ]; then
  echo "Pulling repository..."
  homesick pull
else
  echo "Cloning repository..."
  homesick clone https://github.com/nicolasmccurdy/dotfiles.git
fi
echo

echo "Switching shell to zsh..."
if [ "$SHELL" != "/bin/zsh" ]; then
  if [ "$(uname)" = "Darwin" ]; then
    chsh -s /bin/zsh
  else
    sudo chsh --shell /bin/zsh "$(whoami)"
  fi
fi
echo

echo "Symlinking config files..."
homesick symlink
echo

echo "Setting up ~/Repos..."
if [ ! -d "$HOME/Repos" ]; then
  mkdir "$HOME/Repos"
fi
if [ ! -e "$HOME/Repos/dotfiles" ]; then
  ln -s "$HOME/.homesick/repos/dotfiles $HOME/Repos/dotfiles"
fi
echo

echo "Installing plug..."
if [ ! -d "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
echo

echo "Updating vim plugins..."
vim +PlugUpdate +qall
echo

echo "Open a new terminal to start your proper shell."
