#!/bin/sh

echo "Installing homesick..."
gem install homesick

if [ -d "$HOME/.homesick/repos/dotfiles" ]
  echo "Pulling repository..."
  homesick pull
then
  echo "Cloning repository..."
  homesick clone https://github.com/nicolasmccurdy/dotfiles.git
fi

echo "Switching shell to zsh..."
if [[ "$(uname)" == "Darwin" ]]
then
  chsh -s /bin/zsh
else
  sudo chsh --shell /bin/zsh `whoami`
fi

echo "Symlinking config files..."
homesick symlink

echo "Setting up ~/Repos..."
if [ ! -d "$HOME/Repos" ]
then
  mkdir $HOME/Repos
fi
ln -s $HOME/.homesick/repos/dotfiles $HOME/Repos/dotfiles

echo "Installing vundle..."
if [ ! -d "$HOME/.vim/bundle" ]
then
  mkdir $HOME/.vim/bundle
fi
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]
then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

echo "Updating vim plugins..."
vim +PluginInstall! +qall

echo "Open a new terminal to start your proper shell."
