#!/bin/sh

if [ -e "$HOME/Repos/dotfiles" ]; then
  echo "Pulling repository..."
  git -C $HOME/Repos/dotfiles pull
else
  echo "Cloning repository..."
  git clone https://github.com/nickmccurdy/dotfiles.git $HOME/Repos/dotfiles
fi
echo

echo "Switching shell to fish..."
if [ "$SHELL" != "/usr/local/bin/fish" ]; then
  if [ "$(uname)" = "Darwin" ]; then
    chsh -s /usr/local/bin/fish
  else
    sudo chsh --shell /usr/local/bin/fish "$(whoami)"
  fi
fi
echo

echo "Symlinking config files..."
stow home --dir $HOME/Repos/dotfiles --target $HOME
echo

echo "Installing plug..."
if [ ! -d "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
echo

echo "Updating vim plugins..."
vim +PlugUpdate +qall
echo

echo "Open a new terminal to start your proper shell."
