#!/bin/bash
# Runs commands for cleaning various parts of the system.

# Maintenance Tasks:
# - clean pacman cache (keeps the newest cached version of each package)
# - clean profile for Google Chrome (cleans up the user's database)

sudo cacheclean 1
profile-cleaner gc
