#!/bin/bash
# Runs "git status" on every subdirectory of the current directory.

command='
	if ! git diff-index --quiet HEAD --; then
		pwd
		git status --short
	fi
'

find . -type d -name .git -execdir sh -c "$command" \;
