#!/bin/bash
# Runs commands for updating various parts of the system.

exists() {
  command -v $1 > /dev/null
}

# System packages

if exists pacaur; then
  sudo pacaur -Syu
elif exists pacman; then
  sudo pacman -Syu
fi

if exists brew; then
  brew update
  brew upgrade --all
fi

# Language packages

if exists gem; then
  gem update --system
  gem update
fi

if exists npm; then
  npm install npm -g
  npm update -g
fi
